Bump PLONK to `0.6`
dusk-network/schnorr pull request #34
Opened 2021-03-11 23:32 UTC by vlopes11

Resolves #33

2021-03-12 11:09 UTC, ZER0 requested changes
LGTM, few nits but the major issue is the tests is using an unstable feature; we should avoid that.

2021-03-12 11:09 UTC, ZER0 commented on tests/zk.rs
> +#![feature(once_cell)]
Do not use `once_cell` yet. Unless they changed really recently, it's an nightly experimental feature that is still marked as unstable.

It's okay to use night-only feature, but they should be marked as stable.

2021-03-12 13:35 UTC, CPerezz reviewed
LGTM as soon as @ZER0 's nits have been addressed.

2021-03-22 11:33 UTC, vlopes11 commented
N/A

2021-03-22 11:33 UTC, closed without merging