canonical: Update to `v0.6`
dusk-network/schnorr pull request #42
Opened 2021-04-29 13:36 UTC by vlopes11

Canonical 0.6 contains a simplifed interface.

With its update, dusk-plonk brought several API simplifications,
including the ones with the ECC gates.

Resolves #41

2021-04-29 14:51 UTC, CPerezz requested changes
A few things to ammend before merging in the comments. Mostly the CHANGELOG stuff and the release bump.

Also, as for the commit message, I would prefer to follow the standards and continue adding the keywords at the beginning of the commit messages unless we're in workspaces.
So I would go from: `canonical: Update to v0.6` to: `Update canonical from v0.5 to v0.6`.

2021-04-29 14:51 UTC, CPerezz commented on CHANGELOG.md
> +- Update `canonical` from `0.5` to `0.6` #41
Could you add an hyperlink to the issue?

2021-04-29 14:51 UTC, CPerezz commented on Cargo.toml
> +version = "0.7.0-rc.0"
Don't update the version now please. Do it in a separated commit in the `release-0.7` branch once this gets merged.

2021-04-30 07:39 UTC, ZER0 commented
I agreed with all the points mentioned by @CPerezz, therefore I will remove myself from the review so that as soon as they're addressed this PR can be merged (otherwise I will either have to request changes too, and then the PR is blocked twice, or I have to approve it even if want to have the changes applied. And if I will ignore it would still pop up on my reviews queue)

2021-05-01 21:17 UTC, CPerezz approved these changes
LGTM

2021-05-04 18:18 UTC, merged